// src/components/feedback/FeedbackLoading.tsx
interface FeedbackLoadingProps {
	size?: "sm" | "md" | "lg";
	text?: string;
}

const sizeClasses = {
	sm: "w-4 h-4",
	md: "w-8 h-8",
	lg: "w-12 h-12",
};

export default function FeedbackLoading({
	size = "md",
	text,
}: FeedbackLoadingProps) {
	return (
		<div className="flex flex-col items-center justify-center gap-3 py-4">
			<svg
				className={`animate-spin text-blue-600 ${sizeClasses[size]}`}
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
			>
				<circle
					className="opacity-25"
					cx="12"
					cy="12"
					r="10"
					stroke="currentColor"
					strokeWidth="4"
				/>
				<path
					className="opacity-75"
					fill="currentColor"
					d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
				/>
			</svg>
			{text && <span className="text-sm text-gray-500">{text}</span>}
		</div>
	);
}

// app/components/feedback/FeedbackLoading.vue
<script setup lang="ts">
interface Props {
  size?: 'sm' | 'md' | 'lg'
  text?: string
}

const props = withDefaults(defineProps<Props>(), {
  size: 'md',
})

const sizeClasses = {
  sm: 'w-4 h-4',
  md: 'w-8 h-8',
  lg: 'w-12 h-12',
}
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-3 py-4">
    <svg
      class="animate-spin text-blue-600"
      :class="sizeClasses[size]"
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
      <path
        class="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
      />
    </svg>
    <span v-if="text" class="text-sm text-gray-500">{{ text }}</span>
  </div>
</template>
