// app/components/base/BaseInput.vue
<script setup lang="ts">
interface Props {
  modelValue: string | number
  type?: 'text' | 'number' | 'email' | 'password' | 'date'
  label?: string
  placeholder?: string
  error?: string
  disabled?: boolean
  required?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  type: 'text',
  disabled: false,
  required: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string | number]
}>()

const inputId = `input-${Math.random().toString(36).substring(2, 9)}`

function handleInput(event: Event) {
  const target = event.target as HTMLInputElement
  const value = props.type === 'number' ? Number(target.value) : target.value
  emit('update:modelValue', value)
}
</script>

<template>
  <div class="w-full">
    <label
      v-if="label"
      :for="inputId"
      class="block text-sm font-medium text-gray-700 mb-1"
    >
      {{ label }}
      <span v-if="required" class="text-red-500">*</span>
    </label>
    <input
      :id="inputId"
      :type="type"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :required="required"
      class="w-full px-4 py-2 border rounded-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
      :class="[
        error ? 'border-red-500 focus:ring-red-500' : 'border-gray-300',
      ]"
      @input="handleInput"
    >
    <p v-if="error" class="mt-1 text-sm text-red-500">
      {{ error }}
    </p>
  </div>
</template>

// src/components/base/BaseInput.tsx
"use client";

import { useId } from "react";

interface BaseInputProps {
	value: string | number;
	onChange: (value: string | number) => void;
	type?: "text" | "number" | "email" | "password" | "date";
	label?: string;
	placeholder?: string;
	error?: string;
	disabled?: boolean;
	required?: boolean;
	min?: string | number;
	max?: string | number;
	step?: string | number;
}

export default function BaseInput({
	value,
	onChange,
	type = "text",
	label,
	placeholder,
	error,
	disabled = false,
	required = false,
	min,
	max,
	step,
}: BaseInputProps) {
	const inputId = useId();

	function handleInput(event: React.ChangeEvent<HTMLInputElement>) {
		const val =
			type === "number" ? Number(event.target.value) : event.target.value;
		onChange(val);
	}

	return (
		<div className="w-full">
			{label && (
				<label
					htmlFor={inputId}
					className="block text-sm font-medium text-gray-700 mb-1"
				>
					{label}
					{required && <span className="text-red-500"> *</span>}
				</label>
			)}
			<input
				id={inputId}
				type={type}
				value={value}
				placeholder={placeholder}
				disabled={disabled}
				required={required}
				min={min}
				max={max}
				step={step}
				className={`w-full px-4 py-2 border rounded-lg transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed ${error ? "border-red-500 focus:ring-red-500" : "border-gray-300"}`}
				onChange={handleInput}
			/>
			{error && <p className="mt-1 text-sm text-red-500">{error}</p>}
		</div>
	);
}
