// src/components/summary/SummaryMonthly.tsx
import type { Category, MonthlySummary } from "@/types";
import { formatCompact, formatKRW } from "@/lib/currency";
import { formatMonthKR, getCurrentMonth } from "@/lib/date";
import BaseCard from "@/components/base/BaseCard";

interface SummaryMonthlyProps {
	summary: MonthlySummary;
	categories: Category[];
}

export default function SummaryMonthly({
	summary,
	categories,
}: SummaryMonthlyProps) {
	const currentMonth = getCurrentMonth();

	function getCategory(id: number): Category | undefined {
		return categories.find((c) => c.id === id);
	}

	const categoryAmounts: { category: Category; amount: number }[] = [];
	summary.byCategory.forEach((amount, categoryId) => {
		const category = getCategory(categoryId);
		if (category && amount > 0) {
			categoryAmounts.push({ category, amount });
		}
	});

	return (
		<BaseCard className="space-y-4">
			<div className="flex items-center justify-between">
				<h2 className="text-lg font-semibold text-gray-900">
					이번 달 저축
				</h2>
				<span className="text-sm text-gray-500">
					{formatMonthKR(currentMonth)}
				</span>
			</div>

			<div className="text-3xl font-bold text-blue-600">
				{formatKRW(summary.total)}
			</div>

			<div className="space-y-2">
				{categoryAmounts.map((item) => (
					<div
						key={item.category.id}
						className="flex items-center justify-between"
					>
						<div className="flex items-center gap-2">
							<div
								className="w-2 h-2 rounded-full"
								style={{
									backgroundColor: item.category.color,
								}}
							/>
							<span className="text-sm text-gray-600">
								{item.category.name}
							</span>
						</div>
						<span className="text-sm font-medium text-gray-900">
							{formatCompact(item.amount)}
						</span>
					</div>
				))}
			</div>
		</BaseCard>
	);
}

// app/components/summary/SummaryMonthly.vue
<script setup lang="ts">
import type { Category, MonthlySummary } from "~/types";
import { formatCompact, formatKRW } from "~/utils/currency";
import { formatMonthKR, getCurrentMonth } from "~/utils/date";

interface Props {
	summary: MonthlySummary;
	categories: Category[];
}

const props = defineProps<Props>();

const currentMonth = getCurrentMonth();

// Get category by id
function getCategory(id: number): Category | undefined {
	return props.categories.find((c) => c.id === id);
}

// Convert Map to array for iteration
const categoryAmounts = computed(() => {
	const result: { category: Category; amount: number }[] = [];
	props.summary.byCategory.forEach((amount, categoryId) => {
		const category = getCategory(categoryId);
		if (category && amount > 0) {
			result.push({ category, amount });
		}
	});
	return result;
});
</script>

<template>
  <BaseCard class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-lg font-semibold text-gray-900">이번 달 저축</h2>
      <span class="text-sm text-gray-500">{{ formatMonthKR(currentMonth) }}</span>
    </div>

    <div class="text-3xl font-bold text-blue-600">
      {{ formatKRW(summary.total) }}
    </div>

    <div class="space-y-2">
      <div
        v-for="item in categoryAmounts"
        :key="item.category.id"
        class="flex items-center justify-between"
      >
        <div class="flex items-center gap-2">
          <div
            class="w-2 h-2 rounded-full"
            :style="{ backgroundColor: item.category.color }"
          />
          <span class="text-sm text-gray-600">{{ item.category.name }}</span>
        </div>
        <span class="text-sm font-medium text-gray-900">
          {{ formatCompact(item.amount) }}
        </span>
      </div>
    </div>
  </BaseCard>
</template>
