// src/components/investment/InvestmentList.tsx
"use client";

import type { Saving } from "@/types";
import FeedbackEmpty from "@/components/feedback/FeedbackEmpty";
import FeedbackLoading from "@/components/feedback/FeedbackLoading";
import InvestmentListItem from "@/components/investment/InvestmentListItem";

interface InvestmentListProps {
	investments: Saving[];
	loading?: boolean;
	onEdit: (saving: Saving) => void;
	onDelete: (saving: Saving) => void;
}

export default function InvestmentList({
	investments,
	loading = false,
	onEdit,
	onDelete,
}: InvestmentListProps) {
	if (loading) {
		return (
			<div className="py-8 text-center">
				<FeedbackLoading text="불러오는 중..." />
			</div>
		);
	}

	if (investments.length === 0) {
		return (
			<FeedbackEmpty
				title="투자 내역이 없습니다"
				description="새로운 투자를 추가해보세요"
			/>
		);
	}

	return (
		<div className="divide-y divide-gray-100">
			{investments.map((investment) => (
				<InvestmentListItem
					key={investment.id}
					investment={investment}
					onEdit={() => onEdit(investment)}
					onDelete={() => onDelete(investment)}
				/>
			))}
		</div>
	);
}

// app/components/investment/InvestmentList.vue
<script setup lang="ts">
import type { Saving } from "~/types";

interface Props {
	investments: Saving[];
	loading?: boolean;
}

defineProps<Props>();

const emit = defineEmits<{
	edit: [saving: Saving];
	delete: [saving: Saving];
}>();
</script>

<template>
  <div>
    <!-- Loading state -->
    <div v-if="loading" class="py-8 text-center">
      <FeedbackLoading text="불러오는 중..." />
    </div>

    <!-- Empty state -->
    <FeedbackEmpty
      v-else-if="investments.length === 0"
      title="투자 내역이 없습니다"
      description="새로운 투자를 추가해보세요"
    />

    <!-- List -->
    <div v-else class="divide-y divide-gray-100">
      <InvestmentListItem
        v-for="investment in investments"
        :key="investment.id"
        :investment="investment"
        @edit="emit('edit', investment)"
        @delete="emit('delete', investment)"
      />
    </div>
  </div>
</template>
